attributes:
  metadata:
    restrictions:
      - condition: "cluster:net_provider != 'neutron'"
        message: "Please use Neutron Networking"
      - condition: "settings:neutron_advanced_configuration.neutron_dvr.value == true"
        message: "Neutron DVR must be disabled in order to use Astara plugin"
    group: network
    astara_db_password:
        generator: "password"
  astara_mgmt_name:
    value: 'astara_mgmt'
    label: 'Astara Management Network Name'
    weight: 15
    description: 'Set the Astara Management Neutron Network Name'
    type: "text"
  astara_mgmt_ipv6_prefix:
    value: 'fdca:3ba5:a17a:acda::/64'
    label: 'Astara Management IPv6 Prefix'
    description: 'Set the IPv6 Prefix for the Management Network'
    weight: 20
    type: "text"
    regex:
      source: '(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))'
      error: "Invalid IPv6 Prefix"
  astara_mgmt_service_port:
    value: '5000'
    label: 'Astara Management Service Port'
    description: 'Set the Astara Managment Service Port'
    weight: 25
    type: "text"
    regex:
      source: '^([1-9][0-9]{0,3}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-5])$'
      error: "Must specify a management port (ie, 5000)"
  astara_api_port:
    value: '44250'
    label: 'Astara API Service Port'
    description: 'Set the Astara API Service Port'
    weight: 30
    type: "text"
    regex:
      source: '^([1-9][0-9]{0,3}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-5])$'
      error: "Empty API Service Port"
  astara_appliance_image_location:
    value: 'http://tarballs.openstack.org/astara-appliance/images/astara_appliance_mitaka.qcow2'
    label: 'Astara Appliance Image URL'
    description: 'Set the Astara Appliance Image Download URL'
    weight: 35
    type: "text"
